// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCOBHFpBadWq4oXRwVXtqOosC7jaa2eJ8',
    appId: '1:180416419625:web:9ba2421ae37c0f13b58938',
    messagingSenderId: '180416419625',
    projectId: 'amrkos-app',
    authDomain: 'amrkos-app.firebaseapp.com',
    storageBucket: 'amrkos-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf8t1NRVofTOAyOBpE8NSSrxxSwjNsOqg',
    appId: '1:180416419625:android:4f1f6aedd83f9b0cb58938',
    messagingSenderId: '180416419625',
    projectId: 'amrkos-app',
    storageBucket: 'amrkos-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqDgdadk2ylKbYAE4oXgrJyhD41lprGHU',
    appId: '1:180416419625:ios:d4dd579c445a59d1b58938',
    messagingSenderId: '180416419625',
    projectId: 'amrkos-app',
    storageBucket: 'amrkos-app.firebasestorage.app',
    iosBundleId: 'com.example.amrkosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqDgdadk2ylKbYAE4oXgrJyhD41lprGHU',
    appId: '1:180416419625:ios:d4dd579c445a59d1b58938',
    messagingSenderId: '180416419625',
    projectId: 'amrkos-app',
    storageBucket: 'amrkos-app.firebasestorage.app',
    iosBundleId: 'com.example.amrkosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCOBHFpBadWq4oXRwVXtqOosC7jaa2eJ8',
    appId: '1:180416419625:web:d64dfdf5afd9c3dbb58938',
    messagingSenderId: '180416419625',
    projectId: 'amrkos-app',
    authDomain: 'amrkos-app.firebaseapp.com',
    storageBucket: 'amrkos-app.firebasestorage.app',
  );
}
